version: '3.8'

services:
    matthieu-degny-portfolio:
      container_name: matthieu-degny-portfolio
      build:
        context: .
        dockerfile: ./Dockerfile
      restart: always
      volumes:
        - /home/kenny/server/app_node/portfolio_matthieu/:/portfolio_matthieu/
      expose:
        - 80
      labels:
        - traefik.http.routers.matthieu-degny-portfolio.rule=Host(`matthieu-degny-portfolio.site`, `www.matthieu-degny-portfolio.site`)
        - traefik.http.routers.matthieu-degny-portfolio.tls=true
        - traefik.http.routers.matthieu-degny-portfolio.tls.certresolver=lets-encrypt
        - traefik.port=80

networks:
  default:
    external:
      name: web

